<?php
declare(strict_types=1);

return [
    'name' => 'Творческая студия Lappy Art',
    'brand_title' => 'Lappy Art',
    'url' => 'https://lappytoys.kz',
    'phone' => '+77058553873',
    'phone_display' => '+7 (705) 855-38-73',
    'telegram' => 'https://t.me/OlgaLapteva85',
    'telegram_group' => 'https://t.me/lappyart',
    'whatsapp' => 'https://wa.me/77058553873',
    'instagram' => 'https://www.instagram.com/lappy.art',
    'tiktok' => 'https://www.tiktok.com/@lapteva2113',
    'yandex_metrica_id' => '112086282',
    'yandex_verification' => 'bb0e61aa39a334bc',
    'city' => 'Семей',
    'og_image' => '/images/og.jpg?v=2',
    'telegram_handle' => '@OlgaLapteva85',
    'instagram_handle' => '@lappy.art',
    'tiktok_handle' => '@lapteva2113',
    'notify_email' => 'olgalapteva8518@gmail.com',
    'map_embed_url' => 'https://yandex.ru/map-widget/v1/?ll=80.259372%2C50.412826&z=17&oid=124787708385&ol=biz&l=map&lang=ru_RU',
    'map_link' => 'https://yandex.kz/maps/-/CXALURZO',
    'map_2gis' => 'https://2gis.kz/semey/geo/70000001117566804',
    'map_google' => 'https://www.google.com/maps/search/?api=1&query=%D0%A8%D1%83%D0%B3%D0%B0%D0%B5%D0%B2%D0%B0%204%2C%20%D0%A1%D0%B5%D0%BC%D0%B5%D0%B9',
    'stats' => [
        ['key' => 'students', 'value' => '100+', 'icon' => null],
        ['key' => 'directions', 'value' => '6', 'icon' => null],
        ['key' => 'group', 'value' => null, 'icon' => 'users'],
    ],
    'benefits' => [
        ['key' => 'nice', 'icon' => 'heart'],
        ['key' => 'clear', 'icon' => 'book-open'],
        ['key' => 'personal', 'icon' => 'clock'],
    ],
    'schedule' => [
        ['weekday' => 'weekday.tue', 'time' => '16:30–18:00', 'note' => 'schedule.note.individual'],
        ['weekday' => 'weekday.thu', 'time' => '16:30–18:00', 'note' => 'schedule.note.individual'],
        ['weekday' => 'weekday.sat', 'time' => '13:00–14:30 · 14:30–16:00', 'note' => 'schedule.note.group'],
        ['weekday' => 'weekday.sun', 'time' => '13:00–14:30 · 14:30–16:00', 'note' => 'schedule.note.group'],
    ],
    'faq_count' => 5,
    'about_paragraphs' => 8,
    'works' => [
        ['file' => 'chick.jpg', 'alt_ru' => 'Вязаный цыплёнок amigurumi — работа ученицы студии', 'alt_kk' => 'Amigurumi тоқылған балапан — студия оқушысының жұмысы'],
        ['file' => 'bunny.jpg', 'alt_ru' => 'Вязаная голова зайчика amigurumi — работа ученицы студии', 'alt_kk' => 'Amigurumi тоқылған қоянша — студия оқушысының жұмысы'],
        ['file' => 'star.jpg', 'alt_ru' => 'Розовая плюшевая звёздочка — работа ученицы студии', 'alt_kk' => 'Қызғылт жұмсақ жұлдызша — студия оқушысының жұмысы'],
        ['file' => 'dragon.jpg', 'alt_ru' => 'Вязаный дракончик amigurumi — работа ученицы студии', 'alt_kk' => 'Amigurumi тоқылған айдаһарша — студия оқушысының жұмысы'],
        ['file' => 'goose.jpg', 'alt_ru' => 'Вязаный гусь amigurumi — работа ученицы студии', 'alt_kk' => 'Amigurumi тоқылған қаз — студия оқушысының жұмысы'],
        ['file' => 'rope-landscape.jpg', 'alt_ru' => 'Круглое панно-пейзаж на плетёном канате', 'alt_kk' => 'Өрілген арқандағы дөңгелек пейзаж панносы'],
        ['file' => 'macrame-keychain.jpg', 'alt_ru' => 'Макраме-брелок с бахромой — работа ученицы студии', 'alt_kk' => 'Шашақты макраме брелок — студия оқушысының жұмысы'],
        ['file' => 'blueberry-strawberry.jpg', 'alt_ru' => 'Вязаные брелоки-ягодки — работа ученицы студии', 'alt_kk' => 'Тоқылған жидек брелоктары — студия оқушысының жұмысы'],
    ],
    'videos' => [
        ['youtube_id' => 'hYk7mVuqDrk'],
        ['youtube_id' => 'mmq1g60HxA8'],
        ['youtube_id' => 'POJMq4jZDMI'],
    ],
    'nav' => [
        '/#about',
        '/#awards',
        '/#courses',
        '/#master-classes',
        '/#online',
        '/#schedule',
        '/#works',
        '/#instagram',
        '/#tiktok',
        '/#reviews',
        '/#faq',
        '/#contacts',
    ],
];
